version: "3.3"

services:
  dribble-backend:
    container_name: dribble-backend
    build: ./backend
    ports:
      - 3000:3000
    command: '/bin/zsh -c "rm -f ./tmp/pids/server.pid && rails s"'
    depends_on: 
      - mysql
    volumes:
      - ./backend:/opt/dribble
    env_file: dribble.env
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    env_file: dribble.env
  nginx:
    image: nginx:alpine
    ports:
        - 80:80
        - 443:443
    depends_on: 
      - dribble-backend
    volumes:
        - ./frontend/dist:/var/www/public/static
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
      
